// <auto-generated />
using System;
using DAL.EF.App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.EF.App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Domain.App.Isik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Eesnimi")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Isikukood")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lisainfo")
                        .HasMaxLength(1500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OsavotumaksId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Perenimi")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OsavotumaksId");

                    b.ToTable("Isikud");
                });

            modelBuilder.Entity("Domain.App.IsikYritusel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IsikId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JurIsikId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("YritusId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsikId");

                    b.HasIndex("JurIsikId");

                    b.HasIndex("YritusId");

                    b.ToTable("IsikudYritusel");
                });

            modelBuilder.Entity("Domain.App.IsikYrituselRoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RollNimetus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IsikYrituselRollid");
                });

            modelBuilder.Entity("Domain.App.JurIsik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JurIsikLiikId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lisainfo")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OsavotumaksId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Registrikood")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JurIsikLiikId");

                    b.HasIndex("OsavotumaksId");

                    b.ToTable("JurIsikud");
                });

            modelBuilder.Entity("Domain.App.JurIsikLiik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("LiikNimetus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JurIsikLiigid");
                });

            modelBuilder.Entity("Domain.App.Osavotumaks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OsavotumaksuStaatusId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TasumiseViisId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OsavotumaksuStaatusId");

                    b.HasIndex("TasumiseViisId");

                    b.ToTable("Osavotumaksud");
                });

            modelBuilder.Entity("Domain.App.OsavotumaksuStaatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Staatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OsavotumaksuStaatused");
                });

            modelBuilder.Entity("Domain.App.TasumiseViis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ViisNimetus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TasumiseViisid");
                });

            modelBuilder.Entity("Domain.App.Yritus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Algus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Asukoht")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Lopp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Yritused");
                });

            modelBuilder.Entity("Domain.App.Isik", b =>
                {
                    b.HasOne("Domain.App.Osavotumaks", null)
                        .WithMany("Isikud")
                        .HasForeignKey("OsavotumaksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.App.IsikYritusel", b =>
                {
                    b.HasOne("Domain.App.Isik", null)
                        .WithMany("IsikudYritusel")
                        .HasForeignKey("IsikId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.App.JurIsik", null)
                        .WithMany("IsikudYritusel")
                        .HasForeignKey("JurIsikId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.App.Yritus", null)
                        .WithMany("IsikudYritusel")
                        .HasForeignKey("YritusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.App.JurIsik", b =>
                {
                    b.HasOne("Domain.App.JurIsikLiik", null)
                        .WithMany("JurIsikud")
                        .HasForeignKey("JurIsikLiikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.App.Osavotumaks", null)
                        .WithMany("JurIsikud")
                        .HasForeignKey("OsavotumaksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.App.Osavotumaks", b =>
                {
                    b.HasOne("Domain.App.OsavotumaksuStaatus", null)
                        .WithMany("Osavotumaksud")
                        .HasForeignKey("OsavotumaksuStaatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.App.TasumiseViis", null)
                        .WithMany("Osavotumaksud")
                        .HasForeignKey("TasumiseViisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.App.Isik", b =>
                {
                    b.Navigation("IsikudYritusel");
                });

            modelBuilder.Entity("Domain.App.JurIsik", b =>
                {
                    b.Navigation("IsikudYritusel");
                });

            modelBuilder.Entity("Domain.App.JurIsikLiik", b =>
                {
                    b.Navigation("JurIsikud");
                });

            modelBuilder.Entity("Domain.App.Osavotumaks", b =>
                {
                    b.Navigation("Isikud");

                    b.Navigation("JurIsikud");
                });

            modelBuilder.Entity("Domain.App.OsavotumaksuStaatus", b =>
                {
                    b.Navigation("Osavotumaksud");
                });

            modelBuilder.Entity("Domain.App.TasumiseViis", b =>
                {
                    b.Navigation("Osavotumaksud");
                });

            modelBuilder.Entity("Domain.App.Yritus", b =>
                {
                    b.Navigation("IsikudYritusel");
                });
#pragma warning restore 612, 618
        }
    }
}
